from typing import Optional

from pydantic import BaseModel, Field


class QuestionRequest(BaseModel):
    question: str = Field(description="End-user question to submit to the LLM.")
    language: Optional[str] = Field(
        default=None, description="Preferred response language (IETF tag)."
    )


class QuestionResponse(BaseModel):
    answer: str = Field(description="Natural-language reply generated by the LLM.")
    language: str = Field(description="Language used for the answer.")


